version: '2'
services:
    cleandata-app:
        image: cleandata
        external_links:
            - cleandata-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/cleandata
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cleandata-postgresql:
        extends:
            file: postgresql.yml
            service: cleandata-postgresql
